<?php

namespace Database\Seeders;

use App\Models\Product;
use App\Models\Category;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        $products = [
            [
                'name' => 'Herbal Face Cleanser Powder',
                'slug' => 'herbal-face-cleanser-powder',
                'description' => 'Neem, Turmeric & Sandalwood blend - deep cleanse with natural ingredients',
                'price' => 399,
                'quantity' => 50,
                'category_id' => Category::where('slug', 'skincare-face-care')->first()->id,
                'image' => 'https://images.unsplash.com/photo-1556228578-8c89e6adf883?w=500',
            ],
            [
                'name' => 'Oats & Rose Gentle Cleanser',
                'slug' => 'oats-rose-gentle-cleanser',
                'description' => 'Soothing oat and rose powder for sensitive skin',
                'price' => 349,
                'quantity' => 45,
                'category_id' => Category::where('slug', 'skincare-face-care')->first()->id,
                'image' => 'https://images.unsplash.com/photo-1556228578-8c89e6adf883?w=500',
            ],
            [
                'name' => 'Charcoal Detox Cleanser Powder',
                'slug' => 'charcoal-detox-cleanser',
                'description' => 'Activated charcoal for deep pore cleansing',
                'price' => 449,
                'quantity' => 40,
                'category_id' => Category::where('slug', 'skincare-face-care')->first()->id,
                'image' => 'https://images.unsplash.com/photo-1556228578-8c89e6adf883?w=500',
            ],
            [
                'name' => 'Gram Flour Cleanser Mix',
                'slug' => 'gram-flour-cleanser-mix',
                'description' => 'Traditional besan cleanser for radiant skin',
                'price' => 299,
                'quantity' => 60,
                'category_id' => Category::where('slug', 'skincare-face-care')->first()->id,
                'image' => 'https://images.unsplash.com/photo-1556228578-8c89e6adf883?w=500',
            ],
            [
                'name' => 'Turmeric & Sandalwood Glow Pack',
                'slug' => 'turmeric-sandalwood-glow-pack',
                'description' => 'Anti-inflammatory face pack with brightening properties',
                'price' => 399,
                'quantity' => 50,
                'category_id' => Category::where('slug', 'skincare-face-care')->first()->id,
                'image' => 'https://images.unsplash.com/photo-1556228578-8c89e6adf883?w=500',
            ],
            [
                'name' => 'Aloe Vera Freeze-Dried Face Pack',
                'slug' => 'aloe-vera-freeze-dried-pack',
                'description' => 'Ultra-hydrating face pack with freeze-dried aloe',
                'price' => 449,
                'quantity' => 45,
                'category_id' => Category::where('slug', 'skincare-face-care')->first()->id,
                'image' => 'https://images.unsplash.com/photo-1556228578-8c89e6adf883?w=500',
            ],
            [
                'name' => 'Neem Anti-Acne Pack',
                'slug' => 'neem-anti-acne-pack',
                'description' => 'Antibacterial neem and tulsi for acne-prone skin',
                'price' => 379,
                'quantity' => 55,
                'category_id' => Category::where('slug', 'skincare-face-care')->first()->id,
                'image' => 'https://images.unsplash.com/photo-1556228578-8c89e6adf883?w=500',
            ],
            [
                'name' => 'Rose Petal Brightening Pack',
                'slug' => 'rose-petal-brightening-pack',
                'description' => 'Vitamin C rich rose petals for skin brightening',
                'price' => 419,
                'quantity' => 50,
                'category_id' => Category::where('slug', 'skincare-face-care')->first()->id,
                'image' => 'https://images.unsplash.com/photo-1556228578-8c89e6adf883?w=500',
            ],
            [
                'name' => 'Hibiscus Anti-Ageing Pack',
                'slug' => 'hibiscus-anti-ageing-pack',
                'description' => 'Collagen-boosting hibiscus for youthful skin',
                'price' => 459,
                'quantity' => 40,
                'category_id' => Category::where('slug', 'skincare-face-care')->first()->id,
                'image' => 'https://images.unsplash.com/photo-1556228578-8c89e6adf883?w=500',
            ],
            [
                'name' => 'Multani Mitti Clay Pack',
                'slug' => 'multani-mitti-clay-pack',
                'description' => 'Fuller\'s earth clay for oil control and detox',
                'price' => 349,
                'quantity' => 60,
                'category_id' => Category::where('slug', 'skincare-face-care')->first()->id,
                'image' => 'https://images.unsplash.com/photo-1556228578-8c89e6adf883?w=500',
            ],
            [
                'name' => 'Coffee Scrub',
                'slug' => 'coffee-scrub',
                'description' => 'Energizing coffee scrub for smooth skin texture',
                'price' => 349,
                'quantity' => 50,
                'category_id' => Category::where('slug', 'skincare-face-care')->first()->id,
                'image' => 'https://images.unsplash.com/photo-1556228578-8c89e6adf883?w=500',
            ],
            [
                'name' => 'Herbal Scrub with Walnut & Rose',
                'slug' => 'herbal-scrub-walnut-rose',
                'description' => 'Gentle exfoliation with walnut shell and rose',
                'price' => 379,
                'quantity' => 45,
                'category_id' => Category::where('slug', 'skincare-face-care')->first()->id,
                'image' => 'https://images.unsplash.com/photo-1556228578-8c89e6adf883?w=500',
            ],
            [
                'name' => 'Rice Flour Exfoliating Scrub',
                'slug' => 'rice-flour-exfoliating-scrub',
                'description' => 'Gentle rice flour scrub for sensitive skin',
                'price' => 329,
                'quantity' => 55,
                'category_id' => Category::where('slug', 'skincare-face-care')->first()->id,
                'image' => 'https://images.unsplash.com/photo-1556228578-8c89e6adf883?w=500',
            ],
            [
                'name' => 'Freeze-Dried Aloe Hydration Gel',
                'slug' => 'aloe-hydration-gel',
                'description' => 'Lightweight moisturizing gel with freeze-dried aloe',
                'price' => 399,
                'quantity' => 50,
                'category_id' => Category::where('slug', 'skincare-face-care')->first()->id,
                'image' => 'https://images.unsplash.com/photo-1556228578-8c89e6adf883?w=500',
            ],
            [
                'name' => 'Herbal Skin Repair Balm',
                'slug' => 'herbal-skin-repair-balm',
                'description' => 'Nourishing balm for barrier repair and healing',
                'price' => 499,
                'quantity' => 40,
                'category_id' => Category::where('slug', 'skincare-face-care')->first()->id,
                'image' => 'https://images.unsplash.com/photo-1556228578-8c89e6adf883?w=500',
            ],
            [
                'name' => 'Vitamin E Glow Serum',
                'slug' => 'vitamin-e-glow-serum',
                'description' => 'Antioxidant vitamin E serum for luminous skin',
                'price' => 549,
                'quantity' => 35,
                'category_id' => Category::where('slug', 'skincare-face-care')->first()->id,
                'image' => 'https://images.unsplash.com/photo-1556228578-8c89e6adf883?w=500',
            ],
            [
                'name' => 'Rosehip Anti-Ageing Serum',
                'slug' => 'rosehip-anti-ageing-serum',
                'description' => 'Vitamin A & C rich rosehip for fine lines',
                'price' => 599,
                'quantity' => 30,
                'category_id' => Category::where('slug', 'skincare-face-care')->first()->id,
                'image' => 'https://images.unsplash.com/photo-1556228578-8c89e6adf883?w=500',
            ],
            [
                'name' => 'Tea Tree Acne Control Serum',
                'slug' => 'tea-tree-acne-serum',
                'description' => 'Antibacterial tea tree serum for blemish control',
                'price' => 449,
                'quantity' => 45,
                'category_id' => Category::where('slug', 'skincare-face-care')->first()->id,
                'image' => 'https://images.unsplash.com/photo-1556228578-8c89e6adf883?w=500',
            ],
            [
                'name' => 'Shea Butter Lip Balm',
                'slug' => 'shea-butter-lip-balm',
                'description' => 'Deeply moisturizing lip balm with shea butter',
                'price' => 199,
                'quantity' => 80,
                'category_id' => Category::where('slug', 'lip-care')->first()->id,
                'image' => 'https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=500',
            ],
            [
                'name' => 'Beetroot Tinted Lip Balm',
                'slug' => 'beetroot-tinted-lip-balm',
                'description' => 'Natural color with beetroot and shea butter',
                'price' => 249,
                'quantity' => 70,
                'category_id' => Category::where('slug', 'lip-care')->first()->id,
                'image' => 'https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=500',
            ],
            [
                'name' => 'Cocoa Butter Lip Balm',
                'slug' => 'cocoa-butter-lip-balm',
                'description' => 'Rich cocoa butter for soft, supple lips',
                'price' => 219,
                'quantity' => 75,
                'category_id' => Category::where('slug', 'lip-care')->first()->id,
                'image' => 'https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=500',
            ],
            [
                'name' => 'Mint Lip Healing Balm',
                'slug' => 'mint-lip-healing-balm',
                'description' => 'Cooling mint with healing properties',
                'price' => 229,
                'quantity' => 70,
                'category_id' => Category::where('slug', 'lip-care')->first()->id,
                'image' => 'https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=500',
            ],
            [
                'name' => 'Sugar & Honey Lip Scrub',
                'slug' => 'sugar-honey-lip-scrub',
                'description' => 'Gentle exfoliation with sugar and honey',
                'price' => 199,
                'quantity' => 60,
                'category_id' => Category::where('slug', 'lip-care')->first()->id,
                'image' => 'https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=500',
            ],
            [
                'name' => 'Coffee Lip Scrub',
                'slug' => 'coffee-lip-scrub',
                'description' => 'Energizing coffee scrub for lip exfoliation',
                'price' => 219,
                'quantity' => 55,
                'category_id' => Category::where('slug', 'lip-care')->first()->id,
                'image' => 'https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=500',
            ],
            [
                'name' => 'Activated Charcoal Kajal',
                'slug' => 'activated-charcoal-kajal',
                'description' => 'Long-lasting natural kajal with activated charcoal',
                'price' => 299,
                'quantity' => 50,
                'category_id' => Category::where('slug', 'eye-makeup')->first()->id,
                'image' => 'https://images.unsplash.com/photo-1516672511211-a5437a6fc4ef?w=500',
            ],
            [
                'name' => 'Almond Oil Traditional Kajal',
                'slug' => 'almond-oil-kajal',
                'description' => 'Nourishing kajal with organic almond oil',
                'price' => 279,
                'quantity' => 55,
                'category_id' => Category::where('slug', 'eye-makeup')->first()->id,
                'image' => 'https://images.unsplash.com/photo-1516672511211-a5437a6fc4ef?w=500',
            ],
            [
                'name' => 'Herbal Kajal (Castor + Aloe)',
                'slug' => 'herbal-kajal-castor-aloe',
                'description' => 'Soothing kajal with castor oil and aloe',
                'price' => 319,
                'quantity' => 50,
                'category_id' => Category::where('slug', 'eye-makeup')->first()->id,
                'image' => 'https://images.unsplash.com/photo-1516672511211-a5437a6fc4ef?w=500',
            ],
            [
                'name' => 'Aloe & Beeswax Natural Mascara',
                'slug' => 'aloe-beeswax-mascara',
                'description' => 'Conditioning mascara with aloe and beeswax',
                'price' => 399,
                'quantity' => 40,
                'category_id' => Category::where('slug', 'eye-makeup')->first()->id,
                'image' => 'https://images.unsplash.com/photo-1516672511211-a5437a6fc4ef?w=500',
            ],
            [
                'name' => 'Castor Oil Lash Growth Mascara',
                'slug' => 'castor-oil-lash-mascara',
                'description' => 'Lash-boosting mascara with castor oil',
                'price' => 449,
                'quantity' => 35,
                'category_id' => Category::where('slug', 'eye-makeup')->first()->id,
                'image' => 'https://images.unsplash.com/photo-1516672511211-a5437a6fc4ef?w=500',
            ],
            [
                'name' => 'Brow Powder (Cocoa & Charcoal)',
                'slug' => 'brow-powder-cocoa-charcoal',
                'description' => 'Natural brow powder in multiple shades',
                'price' => 299,
                'quantity' => 50,
                'category_id' => Category::where('slug', 'eye-makeup')->first()->id,
                'image' => 'https://images.unsplash.com/photo-1516672511211-a5437a6fc4ef?w=500',
            ],
            [
                'name' => 'Brow Wax (Beeswax & Oils)',
                'slug' => 'brow-wax-beeswax-oils',
                'description' => 'Sculpting brow wax with natural holding power',
                'price' => 279,
                'quantity' => 55,
                'category_id' => Category::where('slug', 'eye-makeup')->first()->id,
                'image' => 'https://images.unsplash.com/photo-1516672511211-a5437a6fc4ef?w=500',
            ],
            [
                'name' => 'Natural Powder Foundation',
                'slug' => 'natural-powder-foundation',
                'description' => 'Arrowroot-based powder with natural coverage',
                'price' => 449,
                'quantity' => 45,
                'category_id' => Category::where('slug', 'face-makeup')->first()->id,
                'image' => 'https://images.unsplash.com/photo-1556228578-8c89e6adf883?w=500',
            ],
            [
                'name' => 'Tinted Loose Powder',
                'slug' => 'tinted-loose-powder',
                'description' => 'Buildable coverage with natural ingredients',
                'price' => 379,
                'quantity' => 50,
                'category_id' => Category::where('slug', 'face-makeup')->first()->id,
                'image' => 'https://images.unsplash.com/photo-1556228578-8c89e6adf883?w=500',
            ],
            [
                'name' => 'Compact Powder',
                'slug' => 'compact-powder',
                'description' => 'Pressed powder for touch-ups on the go',
                'price' => 399,
                'quantity' => 50,
                'category_id' => Category::where('slug', 'face-makeup')->first()->id,
                'image' => 'https://images.unsplash.com/photo-1556228578-8c89e6adf883?w=500',
            ],
            [
                'name' => 'Beetroot Powder Blush',
                'slug' => 'beetroot-powder-blush',
                'description' => 'Natural flush with beetroot powder',
                'price' => 329,
                'quantity' => 55,
                'category_id' => Category::where('slug', 'face-makeup')->first()->id,
                'image' => 'https://images.unsplash.com/photo-1556228578-8c89e6adf883?w=500',
            ],
            [
                'name' => 'Hibiscus Blush',
                'slug' => 'hibiscus-blush',
                'description' => 'Vibrant blush with hibiscus petals',
                'price' => 349,
                'quantity' => 50,
                'category_id' => Category::where('slug', 'face-makeup')->first()->id,
                'image' => 'https://images.unsplash.com/photo-1556228578-8c89e6adf883?w=500',
            ],
            [
                'name' => 'Shea & Cocoa Body Butter',
                'slug' => 'shea-cocoa-body-butter',
                'description' => 'Rich body butter with shea and cocoa',
                'price' => 449,
                'quantity' => 40,
                'category_id' => Category::where('slug', 'body-care')->first()->id,
                'image' => 'https://images.unsplash.com/photo-1556228578-8c89e6adf883?w=500',
            ],
            [
                'name' => 'Solid Lotion Bar',
                'slug' => 'solid-lotion-bar',
                'description' => 'Eco-friendly solid lotion bar with beeswax',
                'price' => 349,
                'quantity' => 50,
                'category_id' => Category::where('slug', 'body-care')->first()->id,
                'image' => 'https://images.unsplash.com/photo-1556228578-8c89e6adf883?w=500',
            ],
            [
                'name' => 'Coffee Body Scrub',
                'slug' => 'coffee-body-scrub',
                'description' => 'Energizing full-body scrub with coffee',
                'price' => 399,
                'quantity' => 45,
                'category_id' => Category::where('slug', 'body-care')->first()->id,
                'image' => 'https://images.unsplash.com/photo-1556228578-8c89e6adf883?w=500',
            ],
            [
                'name' => 'Himalayan Salt Detox Scrub',
                'slug' => 'himalayan-salt-detox-scrub',
                'description' => 'Detoxifying salt scrub with essential oils',
                'price' => 429,
                'quantity' => 40,
                'category_id' => Category::where('slug', 'body-care')->first()->id,
                'image' => 'https://images.unsplash.com/photo-1556228578-8c89e6adf883?w=500',
            ],
            [
                'name' => 'Herbal Bath Powder (Ubtan)',
                'slug' => 'herbal-bath-powder-ubtan',
                'description' => 'Traditional ubtan powder for bath soak',
                'price' => 349,
                'quantity' => 50,
                'category_id' => Category::where('slug', 'body-care')->first()->id,
                'image' => 'https://images.unsplash.com/photo-1556228578-8c89e6adf883?w=500',
            ],
            [
                'name' => 'Hibiscus & Amla Hair Pack',
                'slug' => 'hibiscus-amla-hair-pack',
                'description' => 'Strengthening hair mask with hibiscus and amla',
                'price' => 349,
                'quantity' => 50,
                'category_id' => Category::where('slug', 'hair-care')->first()->id,
                'image' => 'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=500',
            ],
            [
                'name' => 'Herbal Hair Growth Oil',
                'slug' => 'herbal-hair-growth-oil',
                'description' => 'Nourishing oil with amla, coconut & hibiscus',
                'price' => 449,
                'quantity' => 40,
                'category_id' => Category::where('slug', 'hair-care')->first()->id,
                'image' => 'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=500',
            ],
            [
                'name' => 'Castor & Almond Nourishing Oil',
                'slug' => 'castor-almond-oil',
                'description' => 'Rich hair oil for deep nourishment',
                'price' => 399,
                'quantity' => 45,
                'category_id' => Category::where('slug', 'hair-care')->first()->id,
                'image' => 'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=500',
            ],
            [
                'name' => 'Natural Hair Serum',
                'slug' => 'natural-hair-serum',
                'description' => 'Lightweight serum with argan and jojoba oils',
                'price' => 449,
                'quantity' => 40,
                'category_id' => Category::where('slug', 'hair-care')->first()->id,
                'image' => 'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=500',
            ],
            [
                'name' => 'Dry Shampoo Powder',
                'slug' => 'dry-shampoo-powder',
                'description' => 'Oil-absorbing dry shampoo between washes',
                'price' => 299,
                'quantity' => 55,
                'category_id' => Category::where('slug', 'hair-care')->first()->id,
                'image' => 'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=500',
            ],
            [
                'name' => 'Stress Relief Roll-On',
                'slug' => 'stress-relief-roll-on',
                'description' => 'Calming lavender blend for stress relief',
                'price' => 249,
                'quantity' => 60,
                'category_id' => Category::where('slug', 'wellness-aromatherapy')->first()->id,
                'image' => 'https://images.unsplash.com/photo-1600857062241-98e5dba7214e?w=500',
            ],
            [
                'name' => 'Sleep Roll-On',
                'slug' => 'sleep-roll-on',
                'description' => 'Relaxing chamomile for better sleep',
                'price' => 249,
                'quantity' => 60,
                'category_id' => Category::where('slug', 'wellness-aromatherapy')->first()->id,
                'image' => 'https://images.unsplash.com/photo-1600857062241-98e5dba7214e?w=500',
            ],
            [
                'name' => 'Healing Balm (Turmeric)',
                'slug' => 'healing-balm-turmeric',
                'description' => 'Anti-inflammatory balm for skin healing',
                'price' => 349,
                'quantity' => 50,
                'category_id' => Category::where('slug', 'wellness-aromatherapy')->first()->id,
                'image' => 'https://images.unsplash.com/photo-1600857062241-98e5dba7214e?w=500',
            ],
            [
                'name' => 'Aloe Powder',
                'slug' => 'aloe-powder',
                'description' => 'Premium freeze-dried aloe powder',
                'price' => 399,
                'quantity' => 50,
                'category_id' => Category::where('slug', 'freeze-dried-specialty')->first()->id,
                'image' => 'https://images.unsplash.com/photo-1556228578-8c89e6adf883?w=500',
            ],
            [
                'name' => 'Neem Powder',
                'slug' => 'neem-powder',
                'description' => 'Pure freeze-dried neem for Skincare',
                'price' => 379,
                'quantity' => 55,
                'category_id' => Category::where('slug', 'freeze-dried-specialty')->first()->id,
                'image' => 'https://images.unsplash.com/photo-1556228578-8c89e6adf883?w=500',
            ],
            [
                'name' => 'Hibiscus Powder',
                'slug' => 'hibiscus-powder',
                'description' => 'Antioxidant-rich freeze-dried hibiscus',
                'price' => 359,
                'quantity' => 60,
                'category_id' => Category::where('slug', 'freeze-dried-specialty')->first()->id,
                'image' => 'https://images.unsplash.com/photo-1556228578-8c89e6adf883?w=500',
            ],
            [
                'name' => 'Strawberry Powder',
                'slug' => 'strawberry-powder',
                'description' => 'Vitamin C rich freeze-dried strawberry',
                'price' => 399,
                'quantity' => 50,
                'category_id' => Category::where('slug', 'freeze-dried-specialty')->first()->id,
                'image' => 'https://images.unsplash.com/photo-1556228578-8c89e6adf883?w=500',
            ],
            [
                'name' => 'DIY Glow Mask Kit',
                'slug' => 'diy-glow-mask-kit',
                'description' => 'Create your own glow mask with aloe, turmeric & sandalwood',
                'price' => 599,
                'quantity' => 30,
                'category_id' => Category::where('slug', 'diy-skincare-kits')->first()->id,
                'image' => 'https://images.unsplash.com/photo-1607623814075-e51df1bdc82f?w=500',
            ],
            [
                'name' => 'DIY Acne Control Kit',
                'slug' => 'diy-acne-control-kit',
                'description' => 'Mix your own neem, tulsi & clay mask',
                'price' => 649,
                'quantity' => 25,
                'category_id' => Category::where('slug', 'diy-skincare-kits')->first()->id,
                'image' => 'https://images.unsplash.com/photo-1607623814075-e51df1bdc82f?w=500',
            ],
            [
                'name' => 'DIY Herbal Cleanser Kit',
                'slug' => 'diy-herbal-cleanser-kit',
                'description' => 'Create custom cleansers with oats, besan & rose',
                'price' => 549,
                'quantity' => 35,
                'category_id' => Category::where('slug', 'diy-skincare-kits')->first()->id,
                'image' => 'https://images.unsplash.com/photo-1607623814075-e51df1bdc82f?w=500',
            ],
            [
                'name' => 'DIY Lip Balm Kit',
                'slug' => 'diy-lip-balm-kit',
                'description' => 'Make your own lip balms with beeswax & tints',
                'price' => 499,
                'quantity' => 40,
                'category_id' => Category::where('slug', 'diy-skincare-kits')->first()->id,
                'image' => 'https://images.unsplash.com/photo-1607623814075-e51df1bdc82f?w=500',
            ],
            [
                'name' => 'DIY Hair Mask Kit',
                'slug' => 'diy-hair-mask-kit',
                'description' => 'Create hair masks with amla, hibiscus & shikakai',
                'price' => 549,
                'quantity' => 30,
                'category_id' => Category::where('slug', 'diy-skincare-kits')->first()->id,
                'image' => 'https://images.unsplash.com/photo-1607623814075-e51df1bdc82f?w=500',
            ],
            [
                'name' => 'Glow & Radiance Combo',
                'slug' => 'glow-radiance-combo',
                'description' => 'Complete facial with pack, serum & mist',
                'price' => 1299,
                'quantity' => 20,
                'category_id' => Category::where('slug', 'combo-packs')->first()->id,
                'image' => 'https://images.unsplash.com/photo-1556228578-8c89e6adf883?w=500',
            ],
            [
                'name' => 'Acne Care Combo',
                'slug' => 'acne-care-combo',
                'description' => 'Neem pack, tea tree serum & clay mask bundle',
                'price' => 1099,
                'quantity' => 25,
                'category_id' => Category::where('slug', 'combo-packs')->first()->id,
                'image' => 'https://images.unsplash.com/photo-1556228578-8c89e6adf883?w=500',
            ],
            [
                'name' => 'Natural Facial Kit',
                'slug' => 'natural-facial-kit',
                'description' => 'Complete 5-step routine with all essentials',
                'price' => 1899,
                'quantity' => 15,
                'category_id' => Category::where('slug', 'combo-packs')->first()->id,
                'image' => 'https://images.unsplash.com/photo-1556228578-8c89e6adf883?w=500',
            ],
            [
                'name' => 'Bridal Glow Kit',
                'slug' => 'bridal-glow-kit',
                'description' => 'Premium beauty kit with sandalwood, rose & hibiscus',
                'price' => 2299,
                'quantity' => 10,
                'category_id' => Category::where('slug', 'combo-packs')->first()->id,
                'image' => 'https://images.unsplash.com/photo-1556228578-8c89e6adf883?w=500',
            ],
            [
                'name' => 'Body Polishing Combo',
                'slug' => 'body-polishing-combo',
                'description' => 'Coffee scrub + lotion bar for full body care',
                'price' => 799,
                'quantity' => 30,
                'category_id' => Category::where('slug', 'combo-packs')->first()->id,
                'image' => 'https://images.unsplash.com/photo-1556228578-8c89e6adf883?w=500',
            ],
            [
                'name' => 'Hair Repair Combo',
                'slug' => 'hair-repair-combo',
                'description' => 'Hair mask + serum for damaged hair recovery',
                'price' => 849,
                'quantity' => 25,
                'category_id' => Category::where('slug', 'combo-packs')->first()->id,
                'image' => 'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=500',
            ],
            [
                'name' => 'Stress Relief Combo',
                'slug' => 'stress-relief-combo',
                'description' => 'Lavender roll-on + balm for relaxation',
                'price' => 599,
                'quantity' => 35,
                'category_id' => Category::where('slug', 'combo-packs')->first()->id,
                'image' => 'https://images.unsplash.com/photo-1556228578-8c89e6adf883?w=500',
            ],
            [
                'name' => 'Travel Essentials Kit',
                'slug' => 'travel-essentials-kit',
                'description' => 'Portable Skincare with lip balm, serum & mask',
                'price' => 749,
                'quantity' => 30,
                'category_id' => Category::where('slug', 'combo-packs')->first()->id,
                'image' => 'https://images.unsplash.com/photo-1556228578-8c89e6adf883?w=500',
            ],
            [
                'name' => 'Beginner Skincare Kit',
                'slug' => 'beginner-skincare-kit',
                'description' => 'Essential 3-step routine for Skincare beginners',
                'price' => 999,
                'quantity' => 25,
                'category_id' => Category::where('slug', 'combo-packs')->first()->id,
                'image' => 'https://images.unsplash.com/photo-1556228578-8c89e6adf883?w=500',
            ],
        ];

        foreach ($products as $product) {
            Product::create($product);
        }
    }
}
